//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `LaserMulti.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <LaserMulti.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompLaserMulti_LaserMulti_ids[2] =
{
    "::Ice::Object",
    "::RoboCompLaserMulti::LaserMulti"
};
const ::std::string iceC_RoboCompLaserMulti_LaserMulti_ops[] =
{
    "getLaserConfData",
    "getLaserData",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompLaserMulti_LaserMulti_getLaserConfData_name = "getLaserConfData";
const ::std::string iceC_RoboCompLaserMulti_LaserMulti_getLaserData_name = "getLaserData";

}

bool
RoboCompLaserMulti::LaserMulti::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompLaserMulti_LaserMulti_ids, iceC_RoboCompLaserMulti_LaserMulti_ids + 2, s);
}

::std::vector<::std::string>
RoboCompLaserMulti::LaserMulti::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompLaserMulti_LaserMulti_ids[0], &iceC_RoboCompLaserMulti_LaserMulti_ids[2]);
}

::std::string
RoboCompLaserMulti::LaserMulti::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompLaserMulti::LaserMulti::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompLaserMulti::LaserMulti";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompLaserMulti::LaserMulti::_iceD_getLaserConfData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_robotid;
    istr->readAll(iceP_robotid);
    inS.endReadParams();
    LaserConfData ret = this->getLaserConfData(iceP_robotid, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompLaserMulti::LaserMulti::_iceD_getLaserData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_robotid;
    istr->readAll(iceP_robotid);
    inS.endReadParams();
    TLaserData ret = this->getLaserData(iceP_robotid, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompLaserMulti::LaserMulti::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompLaserMulti_LaserMulti_ops, iceC_RoboCompLaserMulti_LaserMulti_ops + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompLaserMulti_LaserMulti_ops)
    {
        case 0:
        {
            return _iceD_getLaserConfData(in, current);
        }
        case 1:
        {
            return _iceD_getLaserData(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompLaserMulti::LaserMultiPrx::_iceI_getLaserConfData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompLaserMulti::LaserConfData>>& outAsync, int iceP_robotid, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompLaserMulti_LaserMulti_getLaserConfData_name);
    outAsync->invoke(iceC_RoboCompLaserMulti_LaserMulti_getLaserConfData_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_robotid);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompLaserMulti::LaserMultiPrx::_iceI_getLaserData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompLaserMulti::TLaserData>>& outAsync, int iceP_robotid, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompLaserMulti_LaserMulti_getLaserData_name);
    outAsync->invoke(iceC_RoboCompLaserMulti_LaserMulti_getLaserData_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_robotid);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompLaserMulti::LaserMultiPrx::_newInstance() const
{
    return ::IceInternal::createProxy<LaserMultiPrx>();
}
/// \endcond

const ::std::string&
RoboCompLaserMulti::LaserMultiPrx::ice_staticId()
{
    return LaserMulti::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompLaserMulti_LaserMulti_getLaserConfData_name = "getLaserConfData";

const ::std::string iceC_RoboCompLaserMulti_LaserMulti_getLaserData_name = "getLaserData";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompLaserMulti::upCast(LaserMulti* p) { return p; }

void
::IceProxy::RoboCompLaserMulti::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< LaserMulti>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new LaserMulti;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompLaserMulti::LaserMulti::_iceI_begin_getLaserConfData(::Ice::Int iceP_robotid, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompLaserMulti_LaserMulti_getLaserConfData_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompLaserMulti_LaserMulti_getLaserConfData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompLaserMulti_LaserMulti_getLaserConfData_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_robotid);
        result->endWriteParams();
        result->invoke(iceC_RoboCompLaserMulti_LaserMulti_getLaserConfData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompLaserMulti::LaserConfData
IceProxy::RoboCompLaserMulti::LaserMulti::end_getLaserConfData(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompLaserMulti_LaserMulti_getLaserConfData_name);
    ::RoboCompLaserMulti::LaserConfData ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompLaserMulti::LaserMulti::_iceI_begin_getLaserData(::Ice::Int iceP_robotid, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompLaserMulti_LaserMulti_getLaserData_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompLaserMulti_LaserMulti_getLaserData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompLaserMulti_LaserMulti_getLaserData_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_robotid);
        result->endWriteParams();
        result->invoke(iceC_RoboCompLaserMulti_LaserMulti_getLaserData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompLaserMulti::TLaserData
IceProxy::RoboCompLaserMulti::LaserMulti::end_getLaserData(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompLaserMulti_LaserMulti_getLaserData_name);
    ::RoboCompLaserMulti::TLaserData ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompLaserMulti::LaserMulti::_newInstance() const
{
    return new LaserMulti;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompLaserMulti::LaserMulti::ice_staticId()
{
    return ::RoboCompLaserMulti::LaserMulti::ice_staticId();
}

RoboCompLaserMulti::LaserMulti::~LaserMulti()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompLaserMulti::upCast(LaserMulti* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompLaserMulti_LaserMulti_ids[2] =
{
    "::Ice::Object",
    "::RoboCompLaserMulti::LaserMulti"
};

}

bool
RoboCompLaserMulti::LaserMulti::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompLaserMulti_LaserMulti_ids, iceC_RoboCompLaserMulti_LaserMulti_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompLaserMulti::LaserMulti::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompLaserMulti_LaserMulti_ids[0], &iceC_RoboCompLaserMulti_LaserMulti_ids[2]);
}

const ::std::string&
RoboCompLaserMulti::LaserMulti::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompLaserMulti::LaserMulti::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompLaserMulti::LaserMulti";
    return typeId;
#else
    return iceC_RoboCompLaserMulti_LaserMulti_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompLaserMulti::LaserMulti::_iceD_getLaserConfData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_robotid;
    istr->read(iceP_robotid);
    inS.endReadParams();
    LaserConfData ret = this->getLaserConfData(iceP_robotid, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompLaserMulti::LaserMulti::_iceD_getLaserData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_robotid;
    istr->read(iceP_robotid);
    inS.endReadParams();
    TLaserData ret = this->getLaserData(iceP_robotid, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompLaserMulti_LaserMulti_all[] =
{
    "getLaserConfData",
    "getLaserData",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
RoboCompLaserMulti::LaserMulti::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompLaserMulti_LaserMulti_all, iceC_RoboCompLaserMulti_LaserMulti_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompLaserMulti_LaserMulti_all)
    {
        case 0:
        {
            return _iceD_getLaserConfData(in, current);
        }
        case 1:
        {
            return _iceD_getLaserData(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompLaserMulti::LaserMulti::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< LaserMulti, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompLaserMulti::LaserMulti::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< LaserMulti, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompLaserMulti::_icePatchObjectPtr(LaserMultiPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = LaserMultiPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(LaserMulti::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
